Repository dnd-side-project/dnd-5th-9-backend, pull requests merged in 2021-08, with the labels that each got.

#53 [Feature/#32] 해당 미팅에 등록된 멤버 리스트를 불러오는 API 구현
  src/meetings/meetings.controller.ts
  src/meetings/meetings.service.ts
Labels: 💡 FEATURE, 💻 SERVER

#54 [Feature/#33] 회원 팀장이 해당 미팅에 등록된 멤버를 삭제하는 API 구현
  src/entities/MeetingMembers.ts
  src/meetings/meetings.controller.ts
  src/meetings/meetings.service.ts
Labels: 💡 FEATURE, 💻 SERVER

#55 [Feature/#39]: 모임 정보를 수정하는 APi 구현
  ormconfig.ts
  src/meetings/dto/update-meeting.dto.ts
  src/meetings/meetings.controller.ts
  src/meetings/meetings.service.ts
Labels: 💡 FEATURE

#59 [Feature/#30] 미팅 장소 결과를 반환하는 API 구현
  package-lock.json
  package.json
  src/database/seeds/default_station.ts
  src/entities/MeetingPlaces.ts
  src/entities/Stations.ts
  src/meetings/dto/create-meeting-place.dto.ts
  src/meetings/meetings.controller.ts
  src/meetings/meetings.module.ts
  src/meetings/meetings.service.ts
Labels: 💡 FEATURE, 💻 SERVER, 🔨 REFACTOR

#63 [Feature/#60] 1차 리팩토링 - 코드 분리, 일관성 있는 코드 구성
  src/lib/resResult.ts
  src/meetings/entities/meeting.entity.ts
  src/meetings/meetings.controller.ts
  src/meetings/meetings.service.ts
Labels: 🔨 REFACTOR, 💻 SERVER

#67 [Feature/#61] 미팅 멤버를 생성하는 API 구현
  src/entities/MeetingMembers.ts
  src/entities/MeetingSchedules.ts
  src/entities/Meetings.ts
  src/entities/UsersToMeetings.ts
  src/meetings/dto/create-meeting-member.dto.ts
  src/meetings/meetings.controller.ts
  src/meetings/meetings.module.ts
  src/meetings/meetings.service.ts
Labels: 💡 FEATURE, 🔨 REFACTOR, 💻 SERVER

#70 [Feature/#68] 해당 미팅의 전체 팀원의 스케줄을 반환하는 API 구현
  src/entities/Meetings.ts
  src/meetings/meetings.controller.ts
  src/meetings/meetings.service.ts
Labels: 💡 FEATURE, 💻 SERVER

#71 [Feature/#69] 팀원의 스케줄을 생성 또는 수정하는(save) API 구현
  src/entities/MeetingMemberSchedules.ts
  src/entities/MeetingSchedules.ts
  src/meetings/dto/update-meeting-schedule.dto.ts
  src/meetings/meetings.controller.ts
  src/meetings/meetings.module.ts
  src/meetings/meetings.service.ts
Labels: 💡 FEATURE, 💻 SERVER

#73 [Feature/#72] API 동작 확인
  src/app.controller.ts
  src/app.service.ts
  src/auth/auth.service.ts
  src/auth/jwt-auth.guard.ts
  src/auth/local.auth.guard.ts
  src/auth/local.serializer.ts
  src/entities/MeetingMemberSchedules.ts
  src/entities/MeetingMembers.ts
  src/entities/MeetingPlaces.ts
  src/entities/UsersToMeetings.ts
  src/meetings/dto/create-meeting-member.dto.ts
  src/meetings/dto/update-meeting-schedule.dto.ts
  src/meetings/meetings.controller.ts
  src/meetings/meetings.service.ts
  src/users/dto/update-user.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: ⛔ BUG, 🔨 REFACTOR, 💻 SERVER

#76 [Feature/#74] Docker 적용
  .dockerignore
  Dockerfile
  docker-compose.yml
  package.json
Labels: 💦 CHORE, 💻 SERVER

#77 [Feature/#75] 자동 배포를 위한 Github Action 추가
  .github/workflows/aws.yml
Labels: 💦 CHORE, 💻 SERVER

#78 [Fix/#75] update script
  .github/workflows/aws.yml
Labels: ⛔ BUG

#80 [Fix/#75] Github Action Script 로직 변경
  .github/workflows/aws.yml
Labels: ⛔ BUG, 💦 CHORE, 💻 SERVER

#81 [Fix/#75] update script
  .github/workflows/aws.yml
Labels: ⛔ BUG, 💦 CHORE, 💻 SERVER

#82 [Fix] modify Dockerfile
  Dockerfile
Labels: ⛔ BUG

#83 [Fix/#74] Docker Compose 설정에 의한 오류 해결
  docker-compose.yml
Labels: ⛔ BUG, 💦 CHORE, 💻 SERVER

#84 [Feature/#75] modify root string for CI/CD test
  src/app.service.ts
Labels: 💻 SERVER

#87 [Feature/#85] meetingId 또는 param을 참조하여 미팅 정보를 반환하는 API 구현
  src/meetings/meetings.controller.ts
  src/meetings/meetings.service.ts
Labels: 💡 FEATURE, 💻 SERVER

#89 [Feature/#88] 인근 지하철역 반환 로직 리팩토링
  src/database/seeds/default_station.ts
  src/meetings/meetings.service.ts
Labels: 🔨 REFACTOR, 💻 SERVER

#91 [Fix/#90] 배포 서버에서 CORS에 의해 client와 통신할 수 없는 문제 해결
  src/main.ts
Labels: ⛔ BUG, 💻 SERVER
