Repository dnd-side-project/dnd-5th-9-backend, pull requests merged in 2021-07, with the labels that each got.

#1 [Feature/init] Migration to TypeScript, ESLint/Prettier 설정 적용
  .eslintrc
  .gitignore
  .prettierrc
  bin/www
  package-lock.json
  package.json
  src/api/controller/user.ctrl.ts
  src/api/index.js
  src/api/index.ts
  src/api/service/users.svc.js
  src/api/service/users.svc.ts
  src/app.ts
  src/config/.env.template
  src/config/index.ts
  src/lib/resResult.js
  src/lib/resResult.ts
  src/models/index.js
  src/socket.ts
  tsconfig.json
Labels: enhancement

#2 [Feature/init] TypeORM 설정 파일 추가, ts-node 도입을 통한 TypeScript 실행
  package.json
  src/app.ts
  src/config/index.ts
  src/entity/User.entity.ts
  src/ormconfig.ts
  tsconfig.json
Labels: enhancement

#3 [Feature/init] 데이터베이스 설정 완료 및 테스트 API 동작 확인
  package-lock.json
  package.json
  src/api/controller/user.ctrl.ts
  src/api/service/users.svc.ts
  src/app.ts
  src/config/index.ts
  src/entity/User.entity.ts
  tsconfig.json
Labels: enhancement

#8 [Refactor] update DB entity file
  src/entity/Metting.ts
  src/entity/Metting_member.ts
  src/entity/Metting_member_schdule.ts
  src/entity/Metting_schdule.ts
  src/entity/Station.ts
  src/entity/User.ts
Labels: 🔨 REFACTOR

#11 [Feature/init ] add entity interface file
  .github/pull_request_template.md
  src/entity/Meeting.ts
  src/entity/Meeting_member.ts
  src/entity/Meeting_member_schdule.ts
  src/entity/Meeting_schdule.ts
  src/entity/Metting.ts
  src/entity/Metting_member.ts
  src/entity/Metting_member_schdule.ts
  src/entity/Metting_schdule.ts
  src/entity/Station.ts
  src/entity/User.ts
  src/ormconfig.ts
  src/types/index.ts
Labels: 🔨 REFACTOR

#13 [Feature/db] Add relation, Fix typo
  src/entity/Meeting.ts
  src/entity/Meeting_member.ts
  src/entity/Meeting_member_schdule.ts
  src/entity/Meeting_member_schedule.ts
  src/entity/Meeting_schedule.ts
  src/entity/Station.ts
  src/entity/User.ts
  src/ormconfig.ts
Labels: 💡 FEATURE, 💦 CHORE, 💻 SERVER

#15 [Feature/result-template] add result template
  src/lib/resResult.ts
Labels: 💡 FEATURE, 💻 SERVER

#17 [Feature/db] User-Meeting Relation 추가, 오타 수정
  src/entity/Meeting.ts
  src/entity/Meeting_member.ts
  src/entity/Meeting_schedule.ts
  src/entity/User.ts
  src/types/index.ts
Labels: 💡 FEATURE, 💻 SERVER

#19 [Refact/nest] nestjs 적용 (#18)
  .eslintrc
  .eslintrc.js
  .gitignore
  .prettierrc
  README.md
  nest-cli.json
  package-lock.json
  package.json
  src/api/controller/user.ctrl.ts
  src/api/index.ts
  src/api/service/user.svc.ts
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/app.ts
  src/config/.env.template
  src/config/index.ts
  src/entities/Meeting.ts
  src/entities/Meeting_member.ts
  src/entities/Meeting_member_schedule.ts
  src/entities/Meeting_schedule.ts
  src/entities/Station.ts
  src/entities/User.ts
  src/lib/resResult.ts
  src/main.ts
  src/ormconfig.ts
  src/types/index.ts
  src/user/dto/create-user.dto.ts
  src/user/dto/update-user.dto.ts
  src/user/user.controller.spec.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
  src/webpack-hmr.config.js
  tsconfig.build.json
  tsconfig.json
Labels: 💡 FEATURE, 💻 SERVER, 🔨 REFACTOR

#21 Feature/nest
  .env.template
  .eslintrc
  .eslintrc.js
  README.md
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  src/ormconfig.ts
  src/user/user.controller.spec.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
Labels: 💻 SERVER, 🔨 REFACTOR

#22 [refact/seeding] 지하철역 정보 씨드데이터 추가
  ormconfig.ts
  package-lock.json
  package.json
  src/app.module.ts
  src/database/seeds/default_station.ts
Labels: 💡 FEATURE, 💻 SERVER, 🔨 REFACTOR

#23 [Feature] apply readonly to column of Station table
  src/entities/Station.ts
Labels: 💡 FEATURE, 💻 SERVER

#25 [Feature/db] 데이터베이스 테이블 수정 및 보완
  ormconfig.ts
  package.json
  src/entities/BaseEntity.ts
  src/entities/Meeting.ts
  src/entities/MeetingMember.ts
  src/entities/MeetingMemberSchedule.ts
  src/entities/MeetingPlace.ts
  src/entities/MeetingSchedule.ts
  src/entities/Station.ts
  src/entities/User.ts
  src/entities/UserToMeeting.ts
Labels: 💡 FEATURE, 💻 SERVER, 🔨 REFACTOR

#34 [Feature/#26] 메일을 전송하는 함수 구현
  .env.template
  package-lock.json
  package.json
  src/lib/sendMail.ts
Labels: 💡 FEATURE, 💻 SERVER

#35 [Feature/#27] 비밀번호 변경 메일을 전송하는 API 구현
  .env.template
  package-lock.json
  package.json
  src/app.module.ts
  src/lib/sendMail.ts
  src/main.ts
  src/user/user.controller.spec.ts
  src/user/user.module.ts
  src/user/user.service.ts
  src/users/dto/check-user.dto.ts
  src/users/dto/create-user.dto.ts
  src/users/dto/update-user.dto.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: 💡 FEATURE, 💻 SERVER

#42 [Feature/#28] 비밀번호를 변경하는 API 구현
  ormconfig.ts
  src/database/seeds/default_station.ts
  src/entities/MeetingMemberSchedules.ts
  src/entities/MeetingMembers.ts
  src/entities/MeetingPlaces.ts
  src/entities/MeetingSchedules.ts
  src/entities/Meetings.ts
  src/entities/Stations.ts
  src/entities/Users.ts
  src/entities/UsersToMeetings.ts
  src/users/dto/update-password.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: 💡 FEATURE, 💻 SERVER, 🔨 REFACTOR

#45 [Feature/#29] 팀원의 위치 정보를 등록하는 API 구현
  src/entities/MeetingPlaces.ts
  src/meetings/dto/create-meeting-place.dto.ts
  src/meetings/meetings.controller.ts
  src/meetings/meetings.service.ts
  src/users/users.service.ts
Labels: 💡 FEATURE, 💻 SERVER

#46 [Feature/#31] 문의 메일을 발송하는 API 구현
  src/app.controller.ts
  src/app.service.ts
  src/lib/sendMail.ts
  src/meetings/dto/create-meeting-place.dto.ts
  src/meetings/meetings.module.ts
Labels: ⛔ BUG, 💡 FEATURE, 💻 SERVER

#47 [update/config] typeOrm logger checking, add http-exception file
  ormconfig.ts
  src/http-exception.filter.ts
  src/main.ts
Labels: 💻 SERVER, 🔨 REFACTOR

#48 [Feature/team]: create meeting(#38)
  ormconfig.ts
  package-lock.json
  package.json
  src/meetings/dto/create-meeting.dto.ts
  src/meetings/meetings.module.ts
  src/meetings/meetings.service.ts
Labels: 💡 FEATURE
